[2023-02-09T08:48:44.325+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag3.bash_command manual__2023-02-09T08:48:43.576418+00:00 [queued]>
[2023-02-09T08:48:44.339+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: crawler-dag3.bash_command manual__2023-02-09T08:48:43.576418+00:00 [queued]>
[2023-02-09T08:48:44.339+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T08:48:44.339+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-02-09T08:48:44.339+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-02-09T08:48:44.360+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): bash_command> on 2023-02-09 08:48:43.576418+00:00
[2023-02-09T08:48:44.366+0000] {standard_task_runner.py:55} INFO - Started process 7256 to run task
[2023-02-09T08:48:44.368+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'crawler-dag3', 'bash_command', 'manual__2023-02-09T08:48:43.576418+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/crawler-dag.py', '--cfg-path', '/tmp/tmpgbul79zk']
[2023-02-09T08:48:44.368+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask bash_command
[2023-02-09T08:48:44.417+0000] {task_command.py:389} INFO - Running <TaskInstance: crawler-dag3.bash_command manual__2023-02-09T08:48:43.576418+00:00 [running]> on host 3d45bdeeaf4a
[2023-02-09T08:48:44.478+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=crawler-dag3
AIRFLOW_CTX_TASK_ID=bash_command
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T08:48:43.576418+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-09T08:48:43.576418+00:00
[2023-02-09T08:48:44.479+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-02-09T08:48:44.479+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/crawler/dmx.py']
[2023-02-09T08:48:44.490+0000] {subprocess.py:86} INFO - Output:
[2023-02-09T08:48:44.687+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-02-09T08:48:44.688+0000] {subprocess.py:93} INFO -   File "/opt/***/crawler/dmx.py", line 7, in <module>
[2023-02-09T08:48:44.688+0000] {subprocess.py:93} INFO -     from webdriver_manager.chrome import ChromeDriverManager
[2023-02-09T08:48:44.688+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'webdriver_manager'
[2023-02-09T08:48:44.705+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-02-09T08:48:44.718+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-02-09T08:48:44.722+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=crawler-dag3, task_id=bash_command, execution_date=20230209T084843, start_date=20230209T084844, end_date=20230209T084844
[2023-02-09T08:48:44.740+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task bash_command (Bash command failed. The command returned a non-zero exit code 1.; 7256)
[2023-02-09T08:48:44.781+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-02-09T08:48:44.801+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
